<a href="https://colab.research.google.com/github/chitrakumarsai/PyTorch-learning/blob/main/PyTorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [87]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.6.0+cu124


In [88]:
# Creating tensors

# Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [89]:
scalar.ndim

0

In [90]:
scalar.item()

7

In [91]:
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [92]:
vector.ndim

1

In [93]:
vector.shape

torch.Size([2])

In [94]:
# MATRIX

MATRIX = torch.tensor([[7 , 4, 5],
                       [9 , 10, 13]])
MATRIX

tensor([[ 7,  4,  5],
        [ 9, 10, 13]])

In [95]:
MATRIX.ndim

2

In [96]:
MATRIX.shape

torch.Size([2, 3])

In [97]:
 MATRIX[0]

tensor([7, 4, 5])

In [98]:
 MATRIX[1]

tensor([ 9, 10, 13])

In [99]:
# TENSOR

TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,4,8]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 8]]])

In [100]:
TENSOR.ndim

3

In [101]:
TENSOR.shape

torch.Size([1, 3, 3])

In [102]:
TENSOR2 = torch.tensor([
[
  [
    [1,2,3],
    [3,4,6],
    [6,7,8]

  ],

  [
    [4,5,6],
    [7,8,9],
    [10,11,12]
  ],
  [
    [14,15,16],
    [20,17,18],
    [21,22,23]
  ]
                      ]
                         ])
TENSOR2

tensor([[[[ 1,  2,  3],
          [ 3,  4,  6],
          [ 6,  7,  8]],

         [[ 4,  5,  6],
          [ 7,  8,  9],
          [10, 11, 12]],

         [[14, 15, 16],
          [20, 17, 18],
          [21, 22, 23]]]])

In [103]:
TENSOR2.ndim

4

In [104]:
TENSOR2.shape

torch.Size([1, 3, 3, 3])

In [105]:
# Random tensors

random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.8694, 0.5677, 0.7411, 0.4294],
        [0.8854, 0.5739, 0.2666, 0.6274],
        [0.2696, 0.4414, 0.2969, 0.8317]])

In [106]:
random_image = torch.rand(size = (3, 224,224))
random_image.shape

torch.Size([3, 224, 224])

In [107]:
zeros = torch.zeros(size = (3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [108]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [109]:
ones = torch.ones(size = (3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [110]:
ones.dtype

torch.float32

In [111]:
## creating range of tensors and tensors - like

one_ten = torch.arange(1,10)

In [112]:
torch.arange(start = 1, end = 10, step = 2)

tensor([1, 3, 5, 7, 9])

In [113]:
# CREATING TENSORS LIKE

ten_zeros = torch.zeros_like(input = one_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0])

In [114]:
torch.ones_like(input = one_ten)

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1])

In [115]:
#Tensor Data types

float_32_tensor = torch.tensor([3.0,4.0,5.9],
                               dtype=None)
float_32_tensor

tensor([3.0000, 4.0000, 5.9000])

In [116]:
float_16_tensor = torch.tensor([3.0,4.0,5.9],
                               dtype=torch.float16,
                               device=None,
                               requires_grad=False)
float_16_tensor

tensor([3.0000, 4.0000, 5.8984], dtype=torch.float16)

In [117]:
float_mul = float_32_tensor * float_16_tensor
float_mul.dtype

torch.float32

In [118]:
# Tensor operations

tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [119]:
tensor_mul = torch.tensor([1,2,3])
tensor_mul * 10

tensor([10, 20, 30])

In [120]:
tensor_div = torch.tensor([1,2,3])
tensor_div/10

tensor([0.1000, 0.2000, 0.3000])

In [121]:
torch.mul(tensor,10)

tensor([10, 20, 30])

In [122]:
torch.add(tensor,10)

tensor([11, 12, 13])

In [123]:
torch.div(tensor,10)

tensor([0.1000, 0.2000, 0.3000])

In [124]:
 %%time

 torch.matmul(tensor,tensor)

CPU times: user 31 µs, sys: 4 µs, total: 35 µs
Wall time: 37.4 µs


tensor(14)

In [125]:
tensor_A = torch.tensor([[1,2],
                        [3,4],
                        [6,7]])

tensor_B = torch.tensor([[9,10],
                        [12,13],
                        [15,16]])

tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

In [127]:
# torch.matmul(tensor_A,tensor_B)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [ ]:
tensor_B.T.shape

In [ ]:
tensorA_BT = torch.matmul(tensor_A,tensor_B.T)
tensorA_BT

In [ ]:
tensorA_BT.shape

In [ ]:
# Tensor aggregation

tensor_A, torch.min(tensor_A) , torch.max(tensor_A)

In [128]:
# Find the mean

torch.mean(tensor_A)

RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

In [ ]:
# should be float for mean

torch.mean(tensor_A.type(torch.float32))

In [ ]:
torch.sum(tensor_A)

In [ ]:
tensor_A

In [ ]:
torch.argmin(tensor_A), torch.argmax(tensor_A)

In [ ]:
#Reshaping stacking (vstack, hstack), sqeezing and usqeezing

import torch

x = torch.arange(1.,10.)
x

In [ ]:
x.shape

In [ ]:
#Add and extra dimension
x_reshaped = x.reshape(3,3) #3*3 = 9 or 1*9 = 9 so only these dimensions are possible
x_reshaped

In [ ]:
z = x.view(1,9)
z, z.shape

In [ ]:
# changing z changes x as view shares the same memory
z[:, 5] = 5
z, x

In [ ]:
#Stacking
x_stack = torch.stack([x,x,x,x], dim = 0)
x_stack

In [ ]:
x_vstacked = torch.vstack([x,x,x,x])
x_vstacked

In [ ]:
x_hstacked = torch.hstack([x,x,x,x])
x_hstacked

In [ ]:
# sqeeze removes single dimensions
x_reshaped = x.reshape(1,9)
x_reshaped, x_reshaped.shape

In [ ]:
x_reshaped.squeeze(), x_reshaped.squeeze().shape

In [ ]:
x_reshaped.unsqueeze(dim = 1), x_reshaped.unsqueeze(dim = 1).shape

In [ ]:
# permute
x_original = torch.rand(size = (224,224,3))
x_original.shape

In [ ]:
x_permute = torch.permute(x_original, (2,0,1))

In [ ]:
x_original[0,0,0] = 2342345

In [ ]:
x_original[0,0,0], x_permute[0,0,0]

In [ ]:
# Indexing
import torch
x = torch.arange(1,10).reshape(1,3,3)
x, x.shape

In [ ]:
x[0]

In [ ]:
x[0 , 0]

In [ ]:
x[0,2]

In [ ]:
x[0,2,2]

In [ ]:
x[:,:, 2]

In [ ]:
# Pytorch and numpy
import torch
import numpy as np
array = np.arange(1.0,8.0)
tensor = torch.from_numpy(array) # warning numpy to torch will be floa64 change to float32
array, tensor

In [ ]:
array += 5
array, tensor

In [ ]:
# Reproducibility/random seed
torch.rand(3,3)

In [ ]:
random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

In [ ]:
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3,4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3,4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

In [ ]:
# Ways of accessing GPUs
!nvidia-smi

In [ ]:
torch.cuda.is_available()

In [ ]:
# Setup device agnostic code

device = "cuda" if torch.cuda.is_available() else "cpu"
device

In [ ]:
torch.cuda.device_count()

In [ ]:
tensor = torch.tensor([1,2,3])
tensor, tensor.device

In [ ]:
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

In [129]:
# numpys only cpu... so cant transform to numpy
tensor_on_gpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [ ]:
tensor_back_to_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_to_cpu