<a href="https://colab.research.google.com/github/chitrakumarsai/PyTorch-learning/blob/main/PyTorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.6.0+cu124


In [2]:
# Creating tensors

# Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim

0

In [4]:
scalar.item()

7

In [5]:
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

In [8]:
# MATRIX

MATRIX = torch.tensor([[7 , 4, 5],
                       [9 , 10, 13]])
MATRIX

tensor([[ 7,  4,  5],
        [ 9, 10, 13]])

In [9]:
MATRIX.ndim

2

In [10]:
MATRIX.shape

torch.Size([2, 3])

In [11]:
 MATRIX[0]

tensor([7, 4, 5])

In [12]:
 MATRIX[1]

tensor([ 9, 10, 13])

In [13]:
# TENSOR

TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,4,8]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 8]]])

In [14]:
TENSOR.ndim

3

In [15]:
TENSOR.shape

torch.Size([1, 3, 3])

In [16]:
TENSOR2 = torch.tensor([
[
  [
    [1,2,3],
    [3,4,6],
    [6,7,8]

  ],

  [
    [4,5,6],
    [7,8,9],
    [10,11,12]
  ],
  [
    [14,15,16],
    [20,17,18],
    [21,22,23]
  ]
                      ]
                         ])
TENSOR2

tensor([[[[ 1,  2,  3],
          [ 3,  4,  6],
          [ 6,  7,  8]],

         [[ 4,  5,  6],
          [ 7,  8,  9],
          [10, 11, 12]],

         [[14, 15, 16],
          [20, 17, 18],
          [21, 22, 23]]]])

In [17]:
TENSOR2.ndim

4

In [18]:
TENSOR2.shape

torch.Size([1, 3, 3, 3])

In [19]:
# Random tensors

random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.3964, 0.9002, 0.0478, 0.9117],
        [0.2083, 0.8423, 0.6193, 0.8700],
        [0.2066, 0.8800, 0.9618, 0.4394]])

In [20]:
random_image = torch.rand(size = (3, 224,224))
random_image.shape

torch.Size([3, 224, 224])

In [21]:
zeros = torch.zeros(size = (3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [22]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [23]:
ones = torch.ones(size = (3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [24]:
ones.dtype

torch.float32

In [25]:
## creating range of tensors and tensors - like

one_ten = torch.arange(1,10)

In [26]:
torch.arange(start = 1, end = 10, step = 2)

tensor([1, 3, 5, 7, 9])

In [27]:
# CREATING TENSORS LIKE

ten_zeros = torch.zeros_like(input = one_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0])

In [28]:
torch.ones_like(input = one_ten)

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1])

In [29]:
#Tensor Data types

float_32_tensor = torch.tensor([3.0,4.0,5.9],
                               dtype=None)
float_32_tensor

tensor([3.0000, 4.0000, 5.9000])

In [30]:
float_16_tensor = torch.tensor([3.0,4.0,5.9],
                               dtype=torch.float16,
                               device=None,
                               requires_grad=False)
float_16_tensor

tensor([3.0000, 4.0000, 5.8984], dtype=torch.float16)

In [31]:
float_mul = float_32_tensor * float_16_tensor
float_mul.dtype

torch.float32

In [32]:
# Tensor operations

tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [33]:
tensor_mul = torch.tensor([1,2,3])
tensor_mul * 10

tensor([10, 20, 30])

In [34]:
tensor_div = torch.tensor([1,2,3])
tensor_div/10

tensor([0.1000, 0.2000, 0.3000])

In [35]:
torch.mul(tensor,10)

tensor([10, 20, 30])

In [36]:
torch.add(tensor,10)

tensor([11, 12, 13])

In [37]:
torch.div(tensor,10)

tensor([0.1000, 0.2000, 0.3000])

In [38]:
 %%time

 torch.matmul(tensor,tensor)

CPU times: user 874 µs, sys: 0 ns, total: 874 µs
Wall time: 7.83 ms


tensor(14)

In [39]:
tensor_A = torch.tensor([[1,2],
                        [3,4],
                        [6,7]])

tensor_B = torch.tensor([[9,10],
                        [12,13],
                        [15,16]])

tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

In [40]:
# torch.matmul(torch_A,torch_B)

In [41]:
tensor_B.T.shape

torch.Size([2, 3])

In [42]:
tensorA_BT = torch.matmul(tensor_A,tensor_B.T)
tensorA_BT

tensor([[ 29,  38,  47],
        [ 67,  88, 109],
        [124, 163, 202]])

In [43]:
tensorA_BT.shape

torch.Size([3, 3])

In [44]:
# Tensor aggregation

tensor_A, torch.min(tensor_A) , torch.max(tensor_A)

(tensor([[1, 2],
         [3, 4],
         [6, 7]]),
 tensor(1),
 tensor(7))

In [45]:
# Find the mean

# torch.mean(tensor_A)

In [46]:
# should be float for mean

torch.mean(tensor_A.type(torch.float32))

tensor(3.8333)

In [47]:
torch.sum(tensor_A)

tensor(23)

In [48]:
tensor_A

tensor([[1, 2],
        [3, 4],
        [6, 7]])

In [49]:
torch.argmin(tensor_A), torch.argmax(tensor_A)

(tensor(0), tensor(5))

In [50]:
#Reshaping stacking (vstack, hstack), sqeezing and usqeezing

import torch

x = torch.arange(1.,10.)
x

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [51]:
x.shape

torch.Size([9])

In [52]:
#Add and extra dimension
x_reshaped = x.reshape(3,3) #3*3 = 9 or 1*9 = 9 so only these dimensions are possible
x_reshaped

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [53]:
z = x.view(1,9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [54]:
# changing z changes x as view shares the same memory
z[:, 5] = 5
z, x

(tensor([[1., 2., 3., 4., 5., 5., 7., 8., 9.]]),
 tensor([1., 2., 3., 4., 5., 5., 7., 8., 9.]))

In [55]:
#Stacking
x_stack = torch.stack([x,x,x,x], dim = 0)
x_stack

tensor([[1., 2., 3., 4., 5., 5., 7., 8., 9.],
        [1., 2., 3., 4., 5., 5., 7., 8., 9.],
        [1., 2., 3., 4., 5., 5., 7., 8., 9.],
        [1., 2., 3., 4., 5., 5., 7., 8., 9.]])

In [56]:
x_vstacked = torch.vstack([x,x,x,x])
x_vstacked

tensor([[1., 2., 3., 4., 5., 5., 7., 8., 9.],
        [1., 2., 3., 4., 5., 5., 7., 8., 9.],
        [1., 2., 3., 4., 5., 5., 7., 8., 9.],
        [1., 2., 3., 4., 5., 5., 7., 8., 9.]])

In [57]:
x_hstacked = torch.hstack([x,x,x,x])
x_hstacked

tensor([1., 2., 3., 4., 5., 5., 7., 8., 9., 1., 2., 3., 4., 5., 5., 7., 8., 9.,
        1., 2., 3., 4., 5., 5., 7., 8., 9., 1., 2., 3., 4., 5., 5., 7., 8., 9.])

In [58]:
# sqeeze removes single dimensions
x_reshaped = x.reshape(1,9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 5., 7., 8., 9.]]), torch.Size([1, 9]))

In [59]:
x_reshaped.squeeze(), x_reshaped.squeeze().shape

(tensor([1., 2., 3., 4., 5., 5., 7., 8., 9.]), torch.Size([9]))

In [60]:
x_reshaped.unsqueeze(dim = 1), x_reshaped.unsqueeze(dim = 1).shape

(tensor([[[1., 2., 3., 4., 5., 5., 7., 8., 9.]]]), torch.Size([1, 1, 9]))

In [61]:
# permute
x_original = torch.rand(size = (224,224,3))
x_original.shape

torch.Size([224, 224, 3])

In [62]:
x_permute = torch.permute(x_original, (2,0,1))

In [63]:
x_original[0,0,0] = 2342345

In [64]:
x_original[0,0,0], x_permute[0,0,0]

(tensor(2342345.), tensor(2342345.))

In [65]:
# Indexing
import torch
x = torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [66]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [67]:
x[0 , 0]

tensor([1, 2, 3])

In [68]:
x[0,2]

tensor([7, 8, 9])

In [69]:
x[0,2,2]

tensor(9)

In [70]:
x[:,:, 2]

tensor([[3, 6, 9]])

In [71]:
# Pytorch and numpy
import torch
import numpy as np
array = np.arange(1.0,8.0)
tensor = torch.from_numpy(array) # warning numpy to torch will be floa64 change to float32
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [72]:
array += 5
array, tensor

(array([ 6.,  7.,  8.,  9., 10., 11., 12.]),
 tensor([ 6.,  7.,  8.,  9., 10., 11., 12.], dtype=torch.float64))

In [73]:
# Reproducibility/random seed
torch.rand(3,3)

tensor([[0.3659, 0.9081, 0.4460],
        [0.3907, 0.0035, 0.4886],
        [0.7278, 0.4866, 0.3330]])

In [74]:
random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.6593, 0.4084, 0.8283, 0.7872],
        [0.2916, 0.8722, 0.5025, 0.5011],
        [0.4316, 0.4664, 0.4333, 0.5746]])
tensor([[0.4822, 0.3310, 0.8522, 0.2711],
        [0.6137, 0.7834, 0.2392, 0.9082],
        [0.9143, 0.0211, 0.6423, 0.7531]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [75]:
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3,4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3,4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


In [78]:
# Ways of accessing GPUs
!nvidia-smi

Sat May 10 20:30:59 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   37C    P8              9W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [79]:
torch.cuda.is_available()

True

In [80]:
# Setup device agnostic code

device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [81]:
torch.cuda.device_count()

1

In [82]:
tensor = torch.tensor([1,2,3])
tensor, tensor.device

(tensor([1, 2, 3]), device(type='cpu'))

In [83]:
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

In [84]:
# numpys only cpu... so cant transform to numpy
# tensor_on_gpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [85]:
tensor_back_to_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_to_cpu

array([1, 2, 3])